package br.com.prodrigues.trabalhopratico.view.gui;

import br.com.prodrigues.trabalhopratico.controle.PrincipalControle;


/**
 *
 * @author alessio
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private static TelaPrincipal tela;
    private PrincipalControle controle;
    
    /**
     * Creates new form TelaPrincipal
     */
    private TelaPrincipal() {
        initComponents();
    }

    /**
     * @param controle
     * @return 
     */
    public static TelaPrincipal getInstance(PrincipalControle controle) {

        if (tela == null){
            tela = new TelaPrincipal();
        }
        tela.controle = controle;
        return tela;                 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mnuPrincipal = new javax.swing.JMenuBar();
        imnCadastro = new javax.swing.JMenu();
        imnCliente = new javax.swing.JMenuItem();
        imnAutor = new javax.swing.JMenuItem();
        imnUsuario = new javax.swing.JMenuItem();
        imnLivro = new javax.swing.JMenuItem();
        imnEditora = new javax.swing.JMenuItem();
        imnRelatorio = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Principal");

        imnCadastro.setText("Cadastros");

        imnCliente.setText("Cliente");
        imnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnClienteActionPerformed(evt);
            }
        });
        imnCadastro.add(imnCliente);

        imnAutor.setText("Autor");
        imnAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnAutorActionPerformed(evt);
            }
        });
        imnCadastro.add(imnAutor);

        imnUsuario.setText("Usuario");
        imnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnUsuarioActionPerformed(evt);
            }
        });
        imnCadastro.add(imnUsuario);

        imnLivro.setText("Livro");
        imnLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnLivroActionPerformed(evt);
            }
        });
        imnCadastro.add(imnLivro);

        imnEditora.setText("Editora");
        imnEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnEditoraActionPerformed(evt);
            }
        });
        imnCadastro.add(imnEditora);

        mnuPrincipal.add(imnCadastro);

        imnRelatorio.setText("Relatorios");
        mnuPrincipal.add(imnRelatorio);

        setJMenuBar(mnuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 657, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void imnAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imnAutorActionPerformed
        controle.iniciaAutorControle();
    }//GEN-LAST:event_imnAutorActionPerformed

    private void imnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imnClienteActionPerformed
        controle.iniciaClienteControle();
    }//GEN-LAST:event_imnClienteActionPerformed

    private void imnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imnUsuarioActionPerformed
        // TODO add your handling code here:
        controle.iniciaUsuarioControle();
    }//GEN-LAST:event_imnUsuarioActionPerformed

    private void imnLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imnLivroActionPerformed
        controle.iniciaLivroControle();
    }//GEN-LAST:event_imnLivroActionPerformed

    private void imnEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imnEditoraActionPerformed
        controle.iniciaEditoraControle();
    }//GEN-LAST:event_imnEditoraActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem imnAutor;
    private javax.swing.JMenu imnCadastro;
    private javax.swing.JMenuItem imnCliente;
    private javax.swing.JMenuItem imnEditora;
    private javax.swing.JMenuItem imnLivro;
    private javax.swing.JMenu imnRelatorio;
    private javax.swing.JMenuItem imnUsuario;
    private javax.swing.JMenuBar mnuPrincipal;
    // End of variables declaration//GEN-END:variables
}
