/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.prodrigues.trabalhopratico.view.gui.tela;

import br.com.prodrigues.trabalhopratico.model.Editora;
import br.com.prodrigues.trabalhopratico.model.Endereco;
import br.com.prodrigues.trabalhopratico.model.Telefone;
import br.com.prodrigues.trabalhopratico.view.IViewCrud;
import br.com.prodrigues.trabalhopratico.view.gui.ViewGuiSimples;
import java.awt.Frame;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
/**
 *
 * @author prorodrigues
 */
public class EditoraTela extends ViewGuiSimples implements IViewCrud<Editora> {

    public static EditoraTela getInstance(Frame parent, boolean modal) {
        if (tela == null) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
             * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(LivroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>
            //</editor-fold>
            return new EditoraTela(parent, modal);
        } else {
            return tela;
        }
    }

    public static EditoraTela getTela() {
        return tela;
    }

    public static void setTela(EditoraTela aTela) {
        tela = aTela;
    }
    
    
    
    /**
     * Creates new form EditoraTela
     * @param parent
     * @param modal
     */
    public EditoraTela(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labTitulo = new javax.swing.JLabel();
        panRodape = new javax.swing.JPanel();
        btnCancel = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        edtName = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        edtEmail = new javax.swing.JTextField();
        edtTelefone = new javax.swing.JFormattedTextField();
        lblTelefone = new javax.swing.JLabel();
        lblTelefoneFixo = new javax.swing.JLabel();
        edtTelefoneFixo = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        lblLogradouroNome = new javax.swing.JLabel();
        lblLocalidadeUF = new javax.swing.JLabel();
        lblBairroDistrito = new javax.swing.JLabel();
        edtLogradouroNome = new javax.swing.JTextField();
        lblCEP = new javax.swing.JLabel();
        edtBairroDistrito = new javax.swing.JTextField();
        edtLocalidadeUF = new javax.swing.JTextField();
        edtCEP = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editora Tela");

        labTitulo.setFont(new java.awt.Font("Nimbus Mono L", 1, 18)); // NOI18N
        labTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labTitulo.setText("Titulo");
        labTitulo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        panRodape.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnCancel.setText("Cancelar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panRodapeLayout = new javax.swing.GroupLayout(panRodape);
        panRodape.setLayout(panRodapeLayout);
        panRodapeLayout.setHorizontalGroup(
            panRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panRodapeLayout.createSequentialGroup()
                .addContainerGap(185, Short.MAX_VALUE)
                .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panRodapeLayout.setVerticalGroup(
            panRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panRodapeLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(panRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnOk))
                .addGap(20, 20, 20))
        );

        lblName.setText("Nome:");

        edtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtNameActionPerformed(evt);
            }
        });

        lblEmail.setText("E-mail:");

        edtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtEmailActionPerformed(evt);
            }
        });

        try {
            edtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblTelefone.setText("Telefone:");

        lblTelefoneFixo.setText("Telefone fixo:");

        try {
            edtTelefoneFixo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTelefone)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(edtName, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                            .addComponent(edtEmail)
                            .addComponent(edtTelefone)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTelefoneFixo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtTelefoneFixo, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(edtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(edtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTelefone)
                    .addComponent(edtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefoneFixo)
                    .addComponent(edtTelefoneFixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço"));

        lblLogradouroNome.setText("Logradouro / Nome:");

        lblLocalidadeUF.setText("localidade / UF:");

        lblBairroDistrito.setText("Bairro / Distrito:");

        edtLogradouroNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtLogradouroNomeActionPerformed(evt);
            }
        });

        lblCEP.setText("CEP:");

        edtLocalidadeUF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtLocalidadeUFActionPerformed(evt);
            }
        });

        edtCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtCEPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogradouroNome)
                    .addComponent(lblBairroDistrito)
                    .addComponent(lblLocalidadeUF)
                    .addComponent(lblCEP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edtLogradouroNome)
                    .addComponent(edtBairroDistrito)
                    .addComponent(edtLocalidadeUF)
                    .addComponent(edtCEP))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLogradouroNome)
                    .addComponent(edtLogradouroNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBairroDistrito)
                    .addComponent(edtBairroDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocalidadeUF)
                    .addComponent(edtLocalidadeUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCEP)
                    .addComponent(edtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panRodape, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panRodape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.setConfirmado(false);
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        if(edtName.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Falta o Nome");
        }
        else{
            this.setConfirmado(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnOkActionPerformed

    private void edtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtNameActionPerformed

    private void edtLogradouroNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtLogradouroNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtLogradouroNomeActionPerformed

    private void edtLocalidadeUFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtLocalidadeUFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtLocalidadeUFActionPerformed

    private void edtCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtCEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtCEPActionPerformed

    private void edtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditoraTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            EditoraTela dialog = new EditoraTela(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOk;
    private javax.swing.JTextField edtBairroDistrito;
    private javax.swing.JTextField edtCEP;
    private javax.swing.JTextField edtEmail;
    private javax.swing.JTextField edtLocalidadeUF;
    private javax.swing.JTextField edtLogradouroNome;
    private javax.swing.JTextField edtName;
    private javax.swing.JFormattedTextField edtTelefone;
    private javax.swing.JFormattedTextField edtTelefoneFixo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labTitulo;
    private javax.swing.JLabel lblBairroDistrito;
    private javax.swing.JLabel lblCEP;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblLocalidadeUF;
    private javax.swing.JLabel lblLogradouroNome;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblTelefoneFixo;
    private javax.swing.JPanel panRodape;
    // End of variables declaration//GEN-END:variables
    private static EditoraTela tela;
    private boolean confirmado = false;

    public boolean isConfirmado() {
        return confirmado;
    }

    public void setConfirmado(boolean confirmado) {
        this.confirmado = confirmado;
    }

    @Override
    public Editora create(Editora object) {
        labTitulo.setText("Cadastro de Autor");
        edtName.setText("");
        edtName.setEditable(true);
        edtName.setEnabled(true);
        
        edtEmail.setText("");
        edtEmail.setEditable(true);
        edtEmail.setEnabled(true);
        
        edtTelefone.setText("");
        edtTelefone.setEditable(true);
        edtTelefone.setEnabled(true);
        
        edtTelefoneFixo.setText("");
        edtTelefoneFixo.setEditable(true);
        edtTelefoneFixo.setEnabled(true);
        //ENDEREÇO
        edtLogradouroNome.setText("");
        edtLogradouroNome.setEditable(true);
        edtLogradouroNome.setEnabled(true);
        
        edtBairroDistrito.setText("");
        edtBairroDistrito.setEditable(true);
        edtBairroDistrito.setEnabled(true);
        
        edtLocalidadeUF.setText("");
        edtLocalidadeUF.setEditable(true);
        edtLocalidadeUF.setEnabled(true);
        
        edtCEP.setText("");
        edtCEP.setEditable(true);
        edtCEP.setEnabled(true);
        
        btnCancel.setVisible(true);
        this.setVisible(true);
        
        return this.getScreenObject();
    }

    @Override
    public void read(Editora object) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public Editora update(Editora object) {
         if(confirmado){
            object.setNamepublisher(edtName.getText());
            object.setEmail(edtEmail.getText());
            Endereco get = object.getEnderecos().get(0);
            get.setLogradouro(edtLogradouroNome.getText());
            get.setLocalidade(edtLocalidadeUF.getText());
            get.setBairro(edtBairroDistrito.getText());
            get.setCep(edtCEP.getText());
            Endereco set = object.getEnderecos().set(0, get);
            set.setEditora(object);
             
            Telefone get1 = object.getTelefones().get(0);
            Telefone get2 = object.getTelefones().get(1);
            
            get1.setNumero(edtTelefone.getText());
            get2.setNumero(edtTelefoneFixo.getText());
            
            Telefone set1 = object.getTelefones().set(0, get1);
            Telefone set2 = object.getTelefones().set(1, get2);
            
            set1.setEditora(object);
            set2.setEditora(object);
             
                
        } else if(!confirmado){
            showMessage("CANCELADO PELO USUÁRIO!");
        }else if (object == null) {
                showMessage("NÃO ENCONTRADO!");
        }else{
                showMessage("ALTERADO COM SUCESSO!");
        }return object;
    }

    @Override
    public boolean delete(Editora object) {
         labTitulo.setText("Cadastro de Editora");
        edtName.setText(object.getNamepublisher());
        edtName.setEditable(false);
        edtName.setEnabled(false);
        
        edtEmail.setText(object.getEmail());
        edtEmail.setEditable(false);
        edtEmail.setEnabled(false);
        
        edtTelefone.setText(object.getTelefones().get(0).getNumero());
        edtTelefone.setEditable(false);
        edtTelefone.setEnabled(false);
        
        edtTelefoneFixo.setText(object.getTelefones().get(0).getNumero());
        edtTelefoneFixo.setEditable(false);
        edtTelefoneFixo.setEnabled(false);
        //ENDEREÇO
        edtLogradouroNome.setText(object.getEnderecos().get(0).getLogradouro());
        edtLogradouroNome.setEditable(false);
        edtLogradouroNome.setEnabled(false);
        
        edtBairroDistrito.setText(object.getEnderecos().get(0).getBairro());
        edtBairroDistrito.setEditable(false);
        edtBairroDistrito.setEnabled(false);
        
        edtLocalidadeUF.setText(object.getEnderecos().get(0).getLocalidade());
        edtLocalidadeUF.setEditable(false);
        edtLocalidadeUF.setEnabled(false);
        
        edtCEP.setText(object.getEnderecos().get(0).getCep());
        edtCEP.setEditable(false);
        edtCEP.setEnabled(false);
        
        btnCancel.setVisible(true);
        this.setVisible(true);
        if (confirmado) {
            edtName.setText(object.getNamepublisher());
            
        edtEmail.setText(object.getEmail());
      
        edtTelefone.setText(object.getTelefones().get(0).getNumero());
        
        edtTelefoneFixo.setText(object.getTelefones().get(0).getNumero());
        //ENDEREÇO
        edtLogradouroNome.setText(object.getEnderecos().get(0).getLogradouro());
        
        edtBairroDistrito.setText(object.getEnderecos().get(0).getBairro());
   
        edtLocalidadeUF.setText(object.getEnderecos().get(0).getLocalidade());
        
        edtCEP.setText(object.getEnderecos().get(0).getCep());
         } else if (!confirmado) {
            showMessage("CANCELADO PELO USUÁRIO!");
            return false;
        } else if (object == null) {
            showMessage("NÃO ENCONTRADO!");
            return false;
        }
        return true;
    }

    @Override
    public Editora getScreenObject() {
        Editora editora = new Editora(edtName.getText(), edtEmail.getText());
        Endereco endereco = new Endereco();
        endereco.setLogradouro(edtLogradouroNome.getText());
        endereco.setBairro(edtBairroDistrito.getText());
        endereco.setLocalidade(edtLocalidadeUF.getText());
        endereco.setCep(edtCEP.getText());
        editora.addEndereco(endereco);
        List<Telefone> telefones = new ArrayList<>();
        Telefone telefonec = new Telefone(edtTelefone.getText());
        Telefone telefoneF = new Telefone(edtTelefoneFixo.getText());
        telefones.add(telefonec);
        telefones.add(telefoneF);
        editora.setTelefones(telefones);
        telefonec.setEditora(editora);
        telefoneF.setEditora(editora);
        endereco.setEditora(editora);
        return editora;
    }

    @Override
    public void limpaTela() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void preparaUpdate(Editora object) {
        labTitulo.setText("Cadastro de Editora");
        edtName.setText(object.getNamepublisher());
        edtName.setEditable(true);
        edtName.setEnabled(true);
        
        edtEmail.setText(object.getEmail());
        edtEmail.setEditable(true);
        edtEmail.setEnabled(true);
        
        edtTelefone.setText(object.getTelefones().get(0).getNumero());
        edtTelefone.setEditable(true);
        edtTelefone.setEnabled(true);
        
        edtTelefoneFixo.setText(object.getTelefones().get(0).getNumero());
        edtTelefoneFixo.setEditable(true);
        edtTelefoneFixo.setEnabled(true);
        //ENDEREÇO
        edtLogradouroNome.setText(object.getEnderecos().get(0).getLogradouro());
        edtLogradouroNome.setEditable(true);
        edtLogradouroNome.setEnabled(true);
        
        edtBairroDistrito.setText(object.getEnderecos().get(0).getBairro());
        edtBairroDistrito.setEditable(true);
        edtBairroDistrito.setEnabled(true);
        
        edtLocalidadeUF.setText(object.getEnderecos().get(0).getLocalidade());
        edtLocalidadeUF.setEditable(true);
        edtLocalidadeUF.setEnabled(true);
        
        edtCEP.setText(object.getEnderecos().get(0).getCep());
        edtCEP.setEditable(true);
        edtCEP.setEnabled(true);
        
        btnCancel.setVisible(true);
        this.setVisible(true);
    }
    
}
